import { NavLink } from "react-router";
import { v4 as uniqueKey } from 'uuid';



function Header() {
    const navLinks = [
        {
            name : "Portfolio",
            linkTo : "/portfolio",
            isActive : false
        },
        {
            name : "Services",
            linkTo : "/services",
            isActive : false
        },
        {
            name : "Resources",
            linkTo : "/resources",
            isActive : false
        },
        {
            name : "Industries",
            linkTo : "/industries",
            isActive : false
        },
        {
            name : "About",
            linkTo : "/about",
            isActive : false
        }
    ];
  return (
    <div className="w-full h-[70px] bg-black-background border-2 flex items-center justify-center">
      <div className="w-[60%] h-full flex justify-between items-center font-wix text-white">


        {/* Logo of the nav Bar is placed here  AND THIS IS NOT GENERATED BY CHATGPT................ */}
        <div id="nav-logo-part" className="text-center">
          <img src="assets/logo.svg" alt="logo" className="h-[50px] w-[50px]" />
        </div>

        {/* This is the center part of the nav Bar.......................... */}
        <div id="nav-center-part" className="flex justify-between items-center w-[70%] px-2">
          {navLinks.map((navLink)=> <NavLink key={uniqueKey()} to={navLink.linkTo}>{navLink.name}</NavLink> )}

          {/* Estimate button......... */}
          <div id="nav-right-part" className="rounded-lg py-2 px-6 bg-red-button">Get Estimate</div>
        </div>
        
      </div>
    </div>
  );
}

export default Header;
