import { NavLink } from "react-router";
import { v4 as uniqueKey } from "uuid";
import { GiHamburgerMenu } from "react-icons/gi";
import { navLinks } from "../utils/constants.js";
import { useEffect } from "react";
import debounce from "lodash/debounce";

function NavBar({ isHamburgerMenuOpen, setIsHamburgerMenuOpen }) {
  const toggleHamburgerMenu = () => {
    setIsHamburgerMenuOpen((prev) => !prev);
  };

  useEffect(() => {
    const handleResize = debounce(
      () => {
        if (window.innerWidth > 766) {
          setIsHamburgerMenuOpen(false);
        }
      }, 300
    );

    window.addEventListener("resize", handleResize);

    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);
  return (
    <div className="w-full h-[70px] bg-black-background border-2 flex items-center justify-center fixed z-50">
      <div className="w-full sm:w-full md:w-[1000px] h-full flex justify-between items-center font-wix text-white">
        {/* Logo of the nav Bar is placed here  AND THIS IS NOT GENERATED BY CHATGPT................ */}
        <button
          id="nav-logo-part"
          className="cursor-pointer"
          onClick={() => {}}
        >
          <img
            src="assets/logo.svg"
            alt="logo"
            className="h-[50px] w-[50px] m-2"
          />
        </button>

        {/* This is the center part of the nav Bar.......................... */}
        <div
          id="nav-center-part"
          className="hidden h-full w-[100%] md:flex justify-between items-center md:w-[70%] px-2"
        >
          {navLinks.map((navLink) => (
            <NavLink
              key={uniqueKey()}
              to={navLink.linkTo}
              className="h-full flex items-center transition duration-500 ease-in-out hover:border-b-3 border-transparent hover:border-red-button "
            >
              {navLink.name}
            </NavLink>
          ))}

          {/* Estimate button......... */}
          <button
            id="nav-right-part"
            className="rounded-lg py-2 px-6 bg-red-button hover:bg-red-500 cursor-pointer"
          >
            Get Estimate
          </button>
        </div>

        {/* Hamburg Menu...........*/}
        {isHamburgerMenuOpen ? (
          <div
            className="md:hidden mr-4 text-3xl cursor-pointer"
            onClick={toggleHamburgerMenu}
          >
            X
          </div>
        ) : (
          <button
            className="md:hidden mr-4 text-3xl cursor-pointer"
            onClick={toggleHamburgerMenu}
          >
            <GiHamburgerMenu />
          </button>
        )}
      </div>
    </div>
  );
}

export default NavBar;
